services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    build:
      context: ./client_user
      dockerfile: Dockerfile
    volumes:
      - ./client_user:/app
      - /app/node_modules
    ports:
      - "5001:5001"
    environment:
      - CHOKIDAR_USEPOLLING=true
    #command: npm run start